version: '3'
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: reference_service:0.1
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
