apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: devops
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: service-references-deployment
  namespace: devops
spec:
  containers:
    - name: microservice-enid
      image: references_service
      ports:
        - containerPort: 8080
      env:
        - name: DJANGO_RUNNING_MIGRATIONS
          valueFrom:
            secretKeyRef:
              name: service-references-secret
              key: DJANGO_RUNNING_MIGRATIONS
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: service-references-secret
              key: DEBUG
  volumes:
    - name: secret-volume
      secret:
        secretName: service-references-secret



---

apiVersion: v1
kind: Service
metadata:
  name: service-references-service
spec:
  selector:
    app: service-references-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: references-service-secret
  namespace: devops
type: Opaque
data:
  DJANGO_RUNNING_MIGRATIONS: VGVzdC1SZW5kZXJpbmdzLU1pZ3JhdGlvbnM9VHJ1ZQ==
  DEBUG: VHJ1ZQ==
  LOCAL: VHJ1ZQ==
  SECRET_KEY: ZGphbmdvLWluc2RlY3VyZS1yOSV4aCEhbng5XyhfaG1jM2FvZSQtaTBzcXA0ODNweXMkczFnJVV0dVxxcXN3c3d3c3NzZWJy
  ALLOWED_HOSTS: MTI3LjAuMC4xLExvY2FsaG9zdA==
  CORS_ALLOWED_ORIGINS: aHR0cDovL2xvY2FsaG9zdCxodHRwOi8vMTI3LjAuMC4x
  DOMAIN: aHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9yZWZlcmVuY2VzLw==
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXJfZGV2OnBhc3NfZHZAb3NzOi81NDMyL2RiX2Rldi9kYl9kZXY=
  POSTGRES_DB: ZGJfZGV2
  POSTGRES_USER: dXNlcl9kZXY=
  POSTGRES_PASSWORD: cGFzc19kdg==
  ENVIRONMENT: ZGV2ZWxvcG1lbnQ=
  SERVICENAME: cmVmZXJlbmNlcyI=