apiVersion: v1
kind: Secret
metadata:
  name: references-service-secret
  namespace: devops
type: Opaque
data:
  DJANGO_RUNNING_MIGRATIONS: VGVzdC1SZW5kZXJpbmdzLU1pZ3JhdGlvbnM9VHJ1ZQ==
  DEBUG: VHJ1ZQ==
  LOCAL: VHJ1ZQ==
  SECRET_KEY: ZGphbmdvLWluc2RlY3VyZS1yOSV4aCEhbng5XyhfaG1jM2FvZSQtaTBzcXA0ODNweXMkczFnJVV0dVxxcXN3c3d3c3NzZWJy
  ALLOWED_HOSTS: MTI3LjAuMC4xLExvY2FsaG9zdA==
  CORS_ALLOWED_ORIGINS: aHR0cDovL2xvY2FsaG9zdCxodHRwOi8vMTI3LjAuMC4x
  DOMAIN: aHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9yZWZlcmVuY2VzLw==
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXJfZGV2OnBhc3NfZHZAb3NzOi81NDMyL2RiX2Rldi9kYl9kZXY=
  POSTGRES_DB: ZGJfZGV2
  POSTGRES_USER: dXNlcl9kZXY=
  POSTGRES_PASSWORD: cGFzc19kdg==
  ENVIRONMENT: ZGV2ZWxvcG1lbnQ=
  SERVICENAME: cmVmZXJlbmNlcyI=
